app/goods/views.py
from flask import Blueprint, render_template, request, g, url_for, session, jsonify
from werkzeug.utils import redirect

from app.user.models import Article, User, Vcomment, Collect, Message
from ext import db

article_app = Blueprint('article', __name__)


def userinfo():
    uid = session['uid']
    user = User.query.filter_by(id=uid).first()
    g.name = user.name
    g.icon = user.icon
    g.id = user.id


@article_app.route('/detail', methods=['GET', 'POST'])
def detail():
    if request.method == 'POST':
        username = request.form.get('username')
        c_name = request.form.get('c_name')
        ocomment = request.form.get('ocomment')
        a_id = request.form.get('a_id')
        print(username, c_name, ocomment, a_id)

        article = Article.query.filter_by(id=a_id).first()
        userinfo()
        comments = Vcomment.query.filter_by(user_id=a_id)

        # 数据校验
        if not all([username, c_name, ocomment, a_id]):
            return render_template('detail.html', article=article, comments=comments, msg='数据不完整')

        article = Article.query.filter_by(id=a_id).first()
        if not article:
            return render_template('detail.html', article=article, comments=comments, msg='文章错误')

        u = User.query.filter_by(name=username).first()
        if not u:
            return render_template('detail.html', article=article, comments=comments, msg='评论对象不存在')

        # v = Vcomment.query.filter_by(v_name=c_name).all()
        # if not v:
        #     return render_template('detail.html', article=article, comments=comments, msg='用户未登录')

        # 信息写入数据库
        vc = Vcomment()
        vc.user_id = u.id
        vc.v_comment = ocomment
        vc.v_con = u.icon
        vc.v_name = c_name
        vc.article_id = a_id

        db.session.add(vc)
        db.session.commit()

        return redirect(url_for('article.detail') + '?a_id=' + a_id)

    a_id = request.args.get('a_id')
    article = Article.query.filter_by(id=a_id).first()
    print('============>', '浏览的文章')
    article.tread = article.tread + 1
    db.session.add(article)
    db.session.commit()

    # if not art.tread:
    #     art.tread = 0
    # art.tread = int(art.tread) + 1
    # db.session.commit(art)
    userinfo()
    comments = Vcomment.query.filter_by(article_id=a_id)

    # 查看是否该用户收藏过的文章
    uid = session['uid']
    collect = Collect.query.filter_by(user_id=uid, article_id=a_id).first()

    return render_template('detail.html', article=article, comments=comments, collect=collect)


@article_app.route('/change', methods=['POST'])
def change():
    a_id = request.form.get('ar_id')
    c_tar = request.form.get('c_tar')

    print(c_tar)

    if not all([a_id, c_tar]):
        return jsonify({'res': 0, 'msg': '数据不完整'})

    article = Article.query.filter_by(id=a_id).first()
    if not article:
        return jsonify({'res': 1, 'msg': '文章不存在'})

    uid = session['uid']

    if c_tar == '0':
        article.g_num = int(article.g_num) + 1
    if c_tar == '1':
        article.l_num = int(article.l_num) + 1
        collect = Collect(user_id=uid, article_id=a_id)
        db.session.add(collect)
    if c_tar == '2':
        article.l_num = int(article.l_num) - 1
        collect = Collect.query.filter_by(user_id=uid, article_id=a_id).first()
        print('走了')
        db.session.delete(collect)

    db.session.add(article)
    db.session.commit()
    return jsonify({'res': 2})


@article_app.route('/leave', methods=['GET','POST'])
def leave():
    if request.method == "POST":
        m_name = request.form.get('m_name')
        user_id = request.form.get('user_id')
        leave = request.form.get('leave')
        print(m_name, user_id, leave)

        # 校验
        buser = User.query.filter_by(id=user_id).first()
        if not buser:
            return render_template('givemessage.html', msg='不存在该用户')

        if not leave:
            return render_template('givemessage.html', msg='留言内容为空')

        me = Message(user_id=user_id, m_name=m_name, m_con=leave)
        db.session.add(me)
        db.session.commit()
        userinfo()
        return render_template('givemessage.html', msg='留言成功')
    userinfo()
    return render_template('givemessage.html')


@article_app.route('/man', methods=['GET','POST'])
def manager():
    if request.method == 'POST':
        a_id = request.form.get('art_id')

        if not a_id:
            return jsonify({'res': 1, 'msg': '参数错误'})

        article = Article.query.filter_by(id=a_id).first()
        if not article:
            return jsonify({'res': 2, 'msg': '文章不存在'})

        # 业务处理
        db.session.delete(article)
        db.session.commit()

        # 返回应答
        return jsonify({'res': 0, 'msg': '删除成功'})

    articles = Article.query.all()
    userinfo()
    return render_template('manager.html', articles=articles)

app/user/views.py
import re

from flask import Blueprint, render_template, request, g, url_for, session, jsonify
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from app.user.models import Article, ArticleType, User, Photo, Message, Collect
from ext import db
from setting import base

user_app = Blueprint('user', __name__)

TYPE = {
    '0': '全部',
    '1': '随笔',
    '2': '生活',
    '3': '程序人生',
    '4': '音乐',
    '5': '其他',
}

TYPE1 = {
    '全部': '0',
    '随笔': '1',
    '生活': '2',
    '程序人生': '3',
    '音乐': '4',
    '其他': '5'
}

request_login_list = ['/', '/center', '/cen', '/aboutme', '/index', '/message', '/photo',
                      '/publish', '/show_me', '/show_photo', '/show_collect', '/givemessage']


# 用户权限验证
@user_app.before_app_first_request
def before_app_first_request():
    print('======> before_app_first_request')


@user_app.before_app_request
def before_app_request():
    print('=========> before_app_request', request.path)

    # 验证
    if request.path in request_login_list:
        try:
            uid = session['uid']
            user = User.query.filter_by(id=uid).first()
            types = ArticleType.query.all()
            mes_num = len(user.message)
            g.name = user.name
            g.icon = user.icon
            g.types = types
            g.message = mes_num

        except Exception as e:
            render_template('login.html')


@user_app.route('/', methods=['GET', 'POST'])
@user_app.route('/index', methods=['GET', 'POST'], endpoint='index')
def index():
    type = request.args.get('type', '0')
    page = request.args.get('page', '1')
    tar = request.args.get('num')
    pages = request.args.get('pages')

    print(tar)
    if tar == 'prev':
        page = 1
    elif tar == 'next':
        page = pages
    page = int(page)

    types = ArticleType.query.all()

    if type == '0':
        paginates = Article.query.order_by(-Article.publish_time).paginate(page=page, per_page=2)

    else:
        paginates = Article.query.filter_by(type_id=type).order_by(-Article.publish_time).paginate(page=page,
                                                                                                   per_page=2)

    g.n = Article.query.count()
    g.tid = type

    try:
        uid = session['uid']
    except:
        return redirect(url_for('user.login'))

    a_n = Article.query.all()
    a_n_1 = Article.query.first()
    for a in a_n[1:]:
        a_n_1.g_num += a.g_num
    g.g_num = a_n_1.g_num

    a_n = Article.query.all()
    a_n_1 = Article.query.first()
    for a in a_n[1:]:
        a_n_1.tread += a.tread
    g.tread = a_n_1.tread

    # print(paginates)
    # print(paginates.items)  # 每一页的有多少对象
    # print(paginates.page)   # 传给模板的页数
    # print(paginates.pages)  # 总页数
    # print(page_num)         # 当前页

    return render_template('index.html', paginates=paginates, types=types, ptype=TYPE[str(type)])


@user_app.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        repassword = request.form.get('repassword')
        phone = request.form.get('phone')
        email = request.form.get('email')

        # 数据校验
        if not all([username, password, repassword, phone, email]):
            return render_template('register.html', msg='数据不完整')

        try:
            user = User.query.filter_by(user=username)
        except:
            return render_template('register.html', msg='该用户已经注册过了')

        if password != repassword:
            return render_template('register.html', msg='两次密码不一致')

        if not re.match(r'^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
            return render_template('register.html', msg='邮箱错误')

        if not re.match(r'^(13[0-9]|14[5|7]|15[0|1|2|3|5|6|7|8|9]|18[0|1|2|3|5|6|7|8|9])\d{8}$', phone):
            return render_template('register.html', msg='电话错误')

        # 密码加密
        password = generate_password_hash(password)

        # 创建数据
        user = User(name=username, password=password, phone=phone, email=email)

        # 写入数据库
        db.session.add(user)
        db.session.commit()

        return redirect(url_for('user.login'))
    return render_template('register.html')


@user_app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        # 数据校验
        if not all([username, password]):
            return render_template('login.html', msg='数据不完整')

        try:
            user = User.query.filter(User.name == username).first()
        except:
            return render_template('login.html', msg='该用户未注册')

        if not check_password_hash(user.password, password):
            return render_template('login.html', msg='密码错误')

        session['uid'] = user.id

        return redirect(url_for('.index'))
    return render_template('login.html')


@user_app.route('/phone', methods=['GET', 'POST'])
def phone():
    phone = request.form.get('phone')
    verify = request.form.get('verify')
    print(phone, verify)
    return render_template('index.html')


@user_app.route('/center', methods=['GET', 'POST'])
def center():
    types = ArticleType.query.all()
    if request.method == 'POST':
        name = request.form.get('username')
        password = request.form.get('password')
        repassword = request.form.get('repassword')
        phone = request.form.get('phone')
        email = request.form.get('email')
        icon = request.files['thum']

        if repassword != password:
            return render_template('center-info.html', msg='两次密码不一致')

        # 判断图片格式是否正确
        fix = icon.filename.split('.')[-1]
        if fix not in ['jpg', 'png', 'dmp']:
            return render_template('center-info.html', msg='图片格式错误')

        # 本地保存图片
        icon.save(base + '/static/img/upload_icon/' + icon.filename)

        # TODO 七牛云图片上传

        # 获取对象
        uid = session['uid']
        user = User.query.filter_by(id=uid).first()

        # 写入数据库
        if name:
            user.name = name
        if password:
            user.password = password
        if phone:
            user.phone = phone
        if email:
            user.email = email
        if icon:
            user.icon = '/static/img/upload_icon/' + icon.filename

        db.session.commit()
        return render_template('center-info.html', msg='修改成功')

    return render_template('center-info.html', types=types)


@user_app.route('/cen', methods=['GET'])
def cen():
    return render_template('center.html')


@user_app.route('/publish', methods=['GET', 'POST'])
def publish():
    if request.method == 'POST':
        title = request.form.get('title')
        type = request.form.get('type')
        print(type)
        content = request.form.get('content')
        types = ArticleType.query.all()

        # 数据校验
        if not all([title, type, content]):
            return render_template('publish.html', types=types, msg='数据不完整')

        if type not in TYPE1.keys():
            return render_template('publish.html', types=types, msg='非法类型')

        # 创建对象
        uid = session['uid']
        article = Article(t_name=title, comment=content, user_id=uid, type_id=TYPE1[type])
        db.session.add(article)
        db.session.commit()
        return render_template('publish.html', types=types, msg='发布成功')

    types = ArticleType.query.all()
    return render_template('publish.html', types=types)


@user_app.route('/photo', methods=['GET', 'POST'])
def photo():
    uid = session['uid']
    if request.method == 'POST':
        tar = request.form.get('tar')
        print(tar)
        if tar == '0':
            photo = request.files['photo']

            if not photo:
                return render_template('photo.html', msg='图片无效')

            # 判断图片格式是否正确
            fix = photo.filename.split('.')[-1]
            if fix not in ['jpg', 'png', 'dmp']:
                return render_template('photo.html', msg='图片格式错误')

            # 本地保存图片
            photo.save(base + '/static/img/upload_photo/' + photo.filename)

            ph = Photo(name='/static/img/upload_photo/' + photo.filename, user_id=uid)
            db.session.add(ph)
            db.session.commit()

            return redirect(url_for('user.photo'))
        elif tar == '1':
            pid = request.form.get('pid')
            photos = Photo.query.filter_by(user_id=uid).all()
            if not pid:
                return render_template('photo.html', photos=photos, msg='图片错误')
            p = Photo.query.filter_by(id=pid).first()
            print(p)
            if not p:
                return render_template('photo.html', photos=photos, msg='图片信息错误')
            db.session.delete(p)
            db.session.commit()
            return jsonify({'res': 1, 'msg': '删除成功'})

    photos = Photo.query.filter_by(user_id=uid).all()
    return render_template('photo.html', photos=photos)


@user_app.route('/message', methods=['GET', 'POST'])
def message():
    if request.method == 'POST':
        m_id = request.form.get('m_id')

        # 校验参数
        if not m_id:
            return jsonify({'res': 0, 'msg': '参数错误'})

        m = Message.query.filter_by(id=m_id).first()
        if not m:
            return jsonify({'res': 1, 'msg': '无效留言'})

        # 业务操作
        db.session.delete(m)
        db.session.commit()
        return jsonify({'res': 2, 'msg': '删除成功'})

    uid = session['uid']
    # message = Message.query.filter_by(user_id=uid).all()

    user = User.query.filter_by(id=uid).first()
    g.m_n = Message.query.count()
    messages = Message.query.filter_by(user_id=uid).all()
    print(message)
    return render_template('message.html', messages=messages)


@user_app.route('/aboutme', methods=['GET', 'POST'])
def aboutme():
    if request.method == 'POST':

templates/center.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset="utf-8">
	<!-- 移动端必有的 -->
	<meta name="viewport" content="width=device-width,user-scalable=no,
	initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">

	<title>个人中心</title>

	<link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">

	<link rel="stylesheet" type="text/css" href="../static/css/index.css">

	<script type="text/javascript" src="../static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="../static/js/bootstrap.min.js"></script>
    


    <script type="text/javascript">
        $(function(){

            flag = false;

            $('#search').click(function(){
                if(flag == false){
                    $('#go').show();
                    flag = true;
                }
                else{
                    $('#go').hide();
                    flag = false;
                }
            })
        })
    </script>


</head>
<body>
		<!-- 导航条 -->
          <div class="navbar navbar-inverse navbar-static-top" style="margin-bottom: 0px;background-color: #f1f1f1;">
          		<div class="container">
          			 <div class="navbar-header">

          			 	<button class="navbar-toggle" data-toggle="collapse" data-target="#menu" style="border: 1px solid #000;background-color: #f1f1f1;">
          			 		<span class="icon_bar" style="color: #000;"><img src="hsduif.jpg" style="width: 20px;height: 20px;border-radius: 50%;background-color: green;"> 欢迎！<span style="color: red;">{{ g.name }}</span> v</span>
          			 	</button>


          			 	<a href="/" class="navbar-brand" style="font-size: 25px;">看吧</a>
                         <span class="navbar-brand" style="color: #000;font-size: 15px;" id="search">搜索</span>
          			 </div>

                     <form class="navbar-form  navbar-right" style="display: none;" id="go">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" name="" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" type="botton">Go<!-- <span class="glyphicon glyphicon-search"> --></span></button>
                                        </span>
                                    </div>
                                </div>
                    </form>

          			 <div class="collapse navbar-collapse"  id='menu'>

	          			 <ul class="nav navbar-nav">
	          			 	<li class="active"><a href="javascript:;">个人中心</a></li>
	          			 	<li><a href="{{ url_for('user.photo')}}">我的相册</a></li>
	          			 	<li><a href="{{ url_for('user.publish')}}">发布文章</a></li>
	          			 	<li><a href="{{ url_for('user.collect')}}">收藏</a></li>
	          			 </ul>

                         
	          		  </div>
          		</div>
          </div>

         <div class="container header-line">
            <div class="row header">
                <p style="margin-left: 40px;margin-top: 30px; font-size: 25px;">个人中心</p>
            </div>
         </div>

         <div class="container" style="text-align: center;">
         		<p style="margin-top: 30px;"><a href="{{ url_for('user.center')}}" style="font-size: 16px;">个人信息 >></a></p>
         		<p style="margin-top: 30px;"><a href="{{ url_for('user.publish')}}" style="font-size: 16px;">发布文章 >></a></p>
	         	<p style="margin-top: 30px;"><a href="{{ url_for('user.collect')}}" style="font-size: 16px;">收藏 >></a></p>
            <p style="margin-top: 30px;"><a href="{{ url_for('user.photo')}}" style="font-size: 16px;">相册管理 >></a></p>
            <p style="margin-top: 30px;"><a href="{{ url_for('article.manager')}}" style="font-size: 16px;">文章管理 >></a></p>
         </div>
		 </div>

		 <a href="/" style="position: absolute;right: 40px;border: 50px;font-size: 20px;text-decoration: underline;">返回</a>
         <div class="navbar_top" style="font-size: 0px;">
                      <p style="display: inline-block;border-top: 1px solid #000; width: 25%;font-size: 20px;text-align: center;" class="col-lg-3 col-md-3 col-sm-3"><a href="/">首页</a></p>
                      <p style="display: inline-block;border-top: 1px solid #000; width: 25%;font-size: 20px;text-align: center;" class="col-lg-3 col-md-3 col-sm-3"><a href="{{ url_for('user.publish')}}">发布</a></p>
                      <p style="display: inline-block;border-top: 1px solid #000; width: 25%;font-size: 20px;text-align: center;" class="col-lg-3 col-md-3 col-sm-3"><a href="{{ url_for('user.collect')}}">收藏</a></p>
                      <p style="display: inline-block;border-top: 1px solid #000; width: 25%;font-size: 20px;text-align: center;" class="col-lg-3 col-md-3 col-sm-3"><a href="javascript:;">我的</a></p>
         </div>

</body>
</html>

templates/detail.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset="utf-8">
	<!-- 移动端必有的 -->
	<meta name="viewport" content="width=device-width,user-scalable=no,
	initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">

	<title>文章</title>

	<link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">

	<link rel="stylesheet" type="text/css" href="../static/css/index.css">

	<script type="text/javascript" src="../static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="../static/js/bootstrap.min.js"></script>
    


    <script type="text/javascript">
        $(function(){

            flag = false;

            $('#search').click(function(){
                if(flag == false){
                    $('#go').show();
                    flag = true;
                }
                else{
                    $('#go').hide();
                    flag = false;
                }
            })

          $('.agree').click(function(){
            let ar_id = $('.ar_id').val();


            $.post("{{ url_for('article.change')}}", {'ar_id': ar_id, 'c_tar': 0}, function(data){

                if(data.res == '2'){
                  window.location.reload();
                }
                else{
                  alert(data.msg)
                }

            })
          })

          $('.like').click(function(){
            let ar_id = $('.ar_id').val();

            let check = $('.check').val();
            alert(check)

            var c_tar = 1;

            if(check == 'false'){
              $('.check').val('true');

            }
            else{
              $('.check').val('false');
              c_tar = 2;

            }

            $.post("{{ url_for('article.change')}}", {'ar_id': ar_id, 'c_tar': c_tar}, function(data){

                if(data.res == '2'){
                  window.location.reload();
                  $('.like').addClass({'color':'red'})
                }
                else{
                  alert(data.msg)
                }

            })
          })
        })
    </script>


</head>
<body>
		<!-- 导航条 -->
          <div class="navbar navbar-inverse navbar-static-top" style="margin-bottom: 0px;background-color: #f1f1f1;">
          		<div class="container">
          			 <div class="navbar-header">

          			 	<button class="navbar-toggle" data-toggle="collapse" data-target="#menu" style="border: 1px solid #000;background-color: #f1f1f1;">
          			 		<span class="icon_bar" style="color: #000;"><img src="hsduif.jpg" style="width: 20px;height: 20px;border-radius: 50%;background-color: green;"> 欢迎！<span style="color: red;">{{ g.name }}</span> v</span>
          			 	</button>


          			 	<a href="/" class="navbar-brand" style="font-size: 25px;">看吧</a>
                         <span class="navbar-brand" style="color: #000;font-size: 15px;" id="search">搜索</span>
          			 </div>

                     <form class="navbar-form  navbar-right" style="display: none;" id="go">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" name="" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" type="botton">Go<!-- <span class="glyphicon glyphicon-search"> --></span></button>
                                        </span>
                                    </div>
                                </div>
                    </form>

          			 <div class="collapse navbar-collapse"  id='menu'>

	          			 <ul class="nav navbar-nav">
	          			 	<li class="active"><a href="javascript:;">个人中心</a></li>
	          			 	<li><a href="{{ url_for('user.photo')}}">我的相册</a></li>
	          			 	<li><a href="{{ url_for('user.publish')}}">发布文章</a></li>
	          			 	<li><a href="{{ url_for('user.collect')}}">收藏</a></li>
	          			 </ul>

                         
	          		  </div>
          		</div>
          </div>

          <a href="{{ url_for('user.index')}}" style="position: absolute;left:20px;margin-top: 15px; font-size: 16px;text-decoration: underline;"><返回</a>

         <div class="container header-line">
            <div class="row header">
                <input type="hidden" value="{{ article.id }}" class="ar_id">
                <p style="margin-left: 40px;margin-top: 60px; font-size: 25px;">{{ article.t_name }}</p>
                <p style="text-align: right;margin-right: 50px;">
                  <span style="margin-right: 10px;cursor: pointer;" class="agree">赞 <em>{{ article.g_num }}</em></span>
                  <span class="like" {% if collect %}style='color:red;'{% endif %}>❤ <em style="cursor: pointer;">{{ article.l_num }}</em></span>
                </p>
                <input type="hidden" value="{% if collect %}true{% else %}false{% endif %}" class="check">

                <div style="margin-left: 40px;padding-right: 16px;">
                   {{ article.comment }}
                </div>
            </div>
         </div>

         <div class="comment" style="margin-top: 50px;padding-bottom: 50px;">
           <ul>
            {% for comment in comments %}
             <li style="list-style: none;width: 100%;overflow: hidden;margin-top: 20px;" class="col-lg-6">
                <div style="float: left;">
                    <p><img src="shdfuis.jpg" style="width: 25px;height: 25px;"> 评论者：{{ comment.v_name }}</p>
                    <p>{{ comment.v_comment }}</p>
                    <p>评论时间：{{ comment.v_p_time}}</p>
                </div>
             </li>
            {% endfor %}
           </ul>
         </div>

		 
         <div class="navbar_top" style="font-size: 0px;">
                      <p style="display: inline-block;border-top: 1px solid #000; width: 25%;font-size: 20px;text-align: center;" class="col-lg-3 col-md-3 col-sm-3"><a href="/">首页</a></p>
                      <p style="display: inline-block;border-top: 1px solid #000; width: 25%;font-size: 20px;text-align: center;" class="col-lg-3 col-md-3 col-sm-3"><a href="{{ url_for('user.publish')}}">发布</a></p>
                      <p style="display: inline-block;border-top: 1px solid #000; width: 25%;font-size: 20px;text-align: center;" class="col-lg-3 col-md-3 col-sm-3"><a href="{{ url_for('user.collect')}}">收藏</a></p>
                      <p style="display: inline-block;border-top: 1px solid #000; width: 25%;font-size: 20px;text-align: center;" class="col-lg-3 col-md-3 col-sm-3"><a href="{{ url_for('user.cen')}}">我的</a></p>
         </div>

</body>
</html>

templates/manager.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset="utf-8">
	<!-- 移动端必有的 -->
	<meta name="viewport" content="width=device-width,user-scalable=no,
	initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">

	<title>文章管理</title>

	<link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">

	<link rel="stylesheet" type="text/css" href="../static/css/index.css">

	<script type="text/javascript" src="../static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="../static/js/bootstrap.min.js"></script>
    


    <script type="text/javascript">
        $(function(){

            flag = false;

            $('#search').click(function(){
                if(flag == false){
                    $('#go').show();
                    flag = true;
                }
                else{
                    $('#go').hide();
                    flag = false;
                }
            })

            $('.delete').click(function(){
                var a_id = $(this).attr('art_id')
                
                $.post('{{url_for("article.manager")}}', {'art_id': a_id}, function(data){
                    if(data.res == 0){
                       alert('删除成功')
                       window.location.reload()
                    }
                    else{
                      alert(data.msg)
                    }
                })

            })
        })

        
    </script>


</head>
<body>
		<!-- 导航条 -->
          <div class="navbar navbar-inverse navbar-static-top" style="margin-bottom: 0px;background-color: #f1f1f1;">
          		<div class="container">
          			 <div class="navbar-header">

          			 	<button class="navbar-toggle" data-toggle="collapse" data-target="#menu" style="border: 1px solid #000;background-color: #f1f1f1;">
          			 		<span class="icon_bar" style="color: #000;"><img src="hsduif.jpg" style="width: 20px;height: 20px;border-radius: 50%;background-color: green;"> 欢迎！<span style="color: red;">{{ g.name }}</span> v</span>
          			 	</button>


          			 	<a href="/" class="navbar-brand" style="font-size: 25px;">看吧</a>
                         <span class="navbar-brand" style="color: #000;font-size: 15px;" id="search">搜索</span>
          			 </div>

                     <form class="navbar-form  navbar-right" style="display: none;" id="go">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" name="" class="form-control">
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" type="botton">Go<!-- <span class="glyphicon glyphicon-search"> --></span></button>
                                        </span>
                                    </div>
                                </div>
                    </form>

          			 <div class="collapse navbar-collapse"  id='menu'>

	          			 <ul class="nav navbar-nav">
	          			 	<li class="active"><a href="javascript:;">个人中心</a></li>
	          			 	<li><a href="{{ url_for('user.photo')}}">我的相册</a></li>
	          			 	<li><a href="{{ url_for('user.publish')}}">发布文章</a></li>
	          			 	<li><a href="{{ url_for('user.collect')}}">收藏</a></li>
	          			 </ul>

                         
	          		  </div>
          		</div>
          </div>

          <a href="{{ url_for('user.index')}}" style="position: absolute;left:20px;margin-top: 15px; font-size: 16px;text-decoration: underline;"><返回</a>

         <div class="container header-line">
            <div class="row header">
                <p style="margin-left: 40px;margin-top: 60px; font-size: 25px;">文章管理</p>
            </div>
         </div>

         <div class="container" style="padding-left: 40px;">
            <ul style="padding:0">
              {% for article in articles %}
              <li style="list-style: none;margin-top: 20px;height: 25px;">
                  <h4 style="float: left;margin:0">{{ article.t_name }}</h4><a href="javascript:;" class="delete" art_id="{{ article.id }}" style="float: right;">删除</a>
              </li>
              {% endfor %}
            </ul>
         </div>

         <div class="navbar_top" style="font-size: 0px;">
                      <p style="display: inline-block;border-top: 1px solid #000; width: 25%;font-size: 20px;text-align: center;" class="col-lg-3 col-md-3 col-sm-3"><a href="/">首页</a></p>
                      <p style="display: inline-block;border-top: 1px solid #000; width: 25%;font-size: 20px;text-align: center;" class="col-lg-3 col-md-3 col-sm-3"><a href="{{ url_for('user.publish')}}">发布</a></p>
                      <p style="display: inline-block;border-top: 1px solid #000; width: 25%;font-size: 20px;text-align: center;" class="col-lg-3 col-md-3 col-sm-3"><a href="javascript:;">收藏</a></p>
                      <p style="display: inline-block;border-top: 1px solid #000; width: 25%;font-size: 20px;text-align: center;" class="col-lg-3 col-md-3 col-sm-3"><a href="{{ url_for('user.cen')}}">我的</a></p>
         </div>

</body>
</html>